[package]
name = "st-image"
version = "0.3.0"
authors = ["Daniel Rammer <hamersaw@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
#gdal = "0.6"
#gdal = { path = "/home/hamersaw/Projects/gdal" }
#gdal-sys = { path = "/home/hamersaw/Projects/gdal/gdal-sys" }
gdal = { git = "https://github.com/hamersaw/gdal", branch = "feature-options" }
gdal-sys = { git = "https://github.com/hamersaw/gdal", branch = "feature-options", package = "gdal-sys" }
